module.exports = function paymentEmail({ name, utrid, phone }) {
  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; padding: 25px; background: #f3f6fc; border-radius: 10px;">
      
      <div style="background:#ffffff; padding: 25px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.05);">

        <h2 style="color:#1a73e8; margin-bottom: 10px; font-size:22px;">
          💳 New Payment Received
        </h2>

        <p style="font-size:15px; color:#333;">
          A new payment has been submitted on the Technexware Digital portal.
        </p>

        <div style="margin-top:20px; padding:15px; background:#f0f5ff; border-left:4px solid #1a73e8; border-radius:6px;">
          <p style="margin:6px 0;"><strong>Name:</strong> ${name}</p>
          <p style="margin:6px 0;"><strong>Phone:</strong> ${phone}</p>
          <p style="margin:6px 0;"><strong>UTR Number:</strong> ${utrid}</p>
        </div>

        <p style="margin-top:20px; font-size:14px; color:#444;">
          The uploaded payment file (screenshot / PDF / document) has been attached with this email.
        </p>

        <hr style="margin:25px 0; border:none; border-top:1px solid #ddd;" />

        <p style="color:#777; font-size:12px;">
          This email was automatically generated by <strong>Technexware Digital</strong>.  
          If you did not expect this message, please ignore it.
        </p>
      </div>

    </div>
  `;
};
